title: Genil P. Montilde
logo: /assets/img/logo.jpg
description: Mobile = 0946-6032-319 <br/> Email = genilmontilde@gmail.com <br/> Skype = nel.montilde
desc2: true
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal


